name: Test build
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install claat
        run: mkdir /tmp/claat && curl --fail -L -o /tmp/claat/claat https://github.com/googlecodelabs/tools/releases/download/v2.2.6/claat-linux-amd64 && chmod 0755 /tmp/claat/claat
      - name: Build
        run: PATH="/tmp/claat:${PATH}" python3 build.py
