name: Test build
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install claat
        run: ./download-claat-linux.sh
      - name: Build
        run: PATH="/tmp/claat:${PATH}" python3 build.py
